/**
 * Created by William Flageol on 2020-04-30.
 */
public class Book {
    // the id if the book
    private int bookNb;

    // constructor
    public Book(int nb) {
        bookNb = nb;
    }

    public int getbooknumber() {
        return this.bookNb;
        
    }

    // this is a redifinition of equals & hashcode
    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Book))
            return false;

        Book b = (Book) o;
        //verify if the id is the same
        return b.bookNb == this.bookNb;
    }

    // When using a hash table, these collections calculate the hash value for a
    // given key using the hashCode() method and use this value internally to store the
    // data so that access operations are much more efficient.
    // Simply put, hashCode() returns an integer value, generated by a hashing
    // algorithm.
    @Override
    public int hashCode() {
        // here we will be simply returning the "id" or number of the book
        return bookNb;
    }
}